### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Gregorio012#1]
[infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Gregorio012/files/14133787/infografia.pdf)

**Comment by Heidi-19** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
